# Backend/Dockerfile

FROM python:3.12

WORKDIR /app

# Instala dependecias
RUN apt update && apt install -y --no-install-recommends \
	gcc \
	libpq-dev \
	&& rm -rf /var/lib/apt/lists/*

# Copia e instala requerimentos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia codigo
COPY . .

# Variavel para o flask
ENV FLASK_APP = run:app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000


EXPOSE 5000

CMD ["flask", "run"]
